# <center>NumPy Sorting and Searching [8 exercises with solution]</center>

### 1. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

Original array: <br> 
[[10 40]<br>
[30 20]]

### 2. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )(b'Pit', 5, 40.11)]

### 3. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal. 

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 ) (b'Pit', 5, 40.11)]

### 4. Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.

### 5. Write a NumPy program to get the indices of the sorted elements of a given array.

Original array:
[1023 5202 6230 1671 1682 5241 4532]

### 6. Write a NumPy program to sort a given complex array using the real part first, then the imaginary part. Go to the editor

Note: "busday" default of Monday through Friday being valid days.

Original array:
[(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]

### 7. Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice). 

Original array:
[ 70 50 20 30 -11 60 50 40]

### 8. Write a NumPy program to sort the specified number of elements from beginning of a given array.

Original array:
[0.39536213 0.11779404 0.32612381 0.16327394 0.98837963 0.25510787 0.01398678 0.15188239 0.12057667 0.67278699]

#### Problem's Source: [https://www.w3resource.com/python-exercises/numpy/python-numpy-sorting-and-searching.php](https://www.w3resource.com/python-exercises/numpy/python-numpy-sorting-and-searching.php)